apiVersion: apps/v1
kind: Deployment
metadata:
  name: walmart-notification-service
  labels:
    app: walmart-notification-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: walmart-notification-service
  template:
    metadata:
      labels:
        app: walmart-notification-service
    spec:
      containers:
        - name: walmart-notification-service
          image: meixie/walmart-notification-service:0.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: walmart-global-config
            - configMapRef:
                name: walmart-notification-config
          ports:
            - containerPort: 8590
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: walmart-notification-service
spec:
  ports:
    - port: 8590
      targetPort: 8590
  selector:
    app: walmart-notification-service