FROM arm64v8/openjdk:8-jre-buster

ARG NAME="eureka-server"
ARG VERSION="0.0.1"

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

COPY ./target/$NAME-$VERSION.jar /app/eureka-server.jar
CMD ["java", "-Xmx200m",  "-jar", "/app/eureka-server.jar"]

EXPOSE 8761
