apiVersion: v1
kind: ConfigMap
metadata:
  name: walmart-global-config
data:
  SW_AGENT_COLLECTOR_BACKEND_SERVICES: "10.176.122.2:11800"
  SW_GRPC_LOG_SERVER_HOST: "10.176.122.2"
  SW_GRPC_LOG_SERVER_PORT: "11800"
  USER_SERVICE_HOST: "walmart-user-service"
  USER_SERVICE_PORT: "8680"
  GOODS_SERVICE_HOST: "walmart-goods-service"
  GOODS_SERVICE_PORT: "8681"
  ORDER_SERVICE_HOST: "walmart-order-service"
  ORDER_SERVICE_PORT: "8580"
  CART_SERVICE_HOST: "walmart-cart-service"
  CART_SERVICE_PORT: "8684"
  WALLET_SERVICE_HOST: "walmart-wallet-service"
  WALLET_SERVICE_PORT: "8685"
  NOTIFICATION_SERVICE_HOST: "walmart-notification-service"
  NOTIFICATION_SERVICE_PORT: "8590"
  LOGISTICS_SERVICE_HOST: "walmart-logistics-service"
  LOGISTICS_SERVICE_PORT: "8530"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: walmart-rabbitmq-config
data:
  rabbitmq.host: "rabbitmq"
  rabbitmq.username: "admin"
  rabbitmq.password: "admin"
  rabbitmq.port: "5672"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: walmart-wallet-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://walmart-wallet-radondb-leader:3306/walmart-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: walmart-user-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://walmart-user-radondb-my-leader:3306/walmart-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: walmart-order-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://walmart-order-radondb-m-leader:3306/walmart-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: walmart-notification-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://walmart-notification-ra-leader:3306/walmart-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: walmart-logistics-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://walmart-logistic-radond-leader:3306/walmart-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: walmart-goods-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://walmart-goods-radondb-m-leader:3306/walmart-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: walmart-cart-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://walmart-cart-radondb-my-leader:3306/walmart-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: walmart-gateway-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://walmart-user-radondb-my-leader:3306/walmart-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
