FROM arm64v8/openjdk:8-jre-buster

ARG NAME="walmart-goods-service"
ARG VERSION="0.0.1"

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

COPY ./target/$NAME-$VERSION.jar /app/walmart-goods-service.jar
CMD ["java", "-Xmx200m",  "-jar", "/app/walmart-goods-service.jar"]

EXPOSE 8681
